P8105 Homework 2
================
Xiaobo Shen
2026-10-07

## Problem 1

``` r
subway_df =
  read_csv(
    "data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
    col_types = cols(
      Route8 = col_character(),
      Route9 = col_character(),
      Route10 = col_character(),
      Route11 = col_character()
    )
  )

head(subway_df)
```

    ## # A tibble: 6 × 32
    ##   Division Line     `Station Name` `Station Latitude` `Station Longitude` Route1
    ##   <chr>    <chr>    <chr>                       <dbl>               <dbl> <chr> 
    ## 1 BMT      4 Avenue 25th St                      40.7               -74.0 R     
    ## 2 BMT      4 Avenue 25th St                      40.7               -74.0 R     
    ## 3 BMT      4 Avenue 36th St                      40.7               -74.0 N     
    ## 4 BMT      4 Avenue 36th St                      40.7               -74.0 N     
    ## 5 BMT      4 Avenue 36th St                      40.7               -74.0 N     
    ## 6 BMT      4 Avenue 45th St                      40.6               -74.0 R     
    ## # ℹ 26 more variables: Route2 <chr>, Route3 <chr>, Route4 <chr>, Route5 <chr>,
    ## #   Route6 <chr>, Route7 <chr>, Route8 <chr>, Route9 <chr>, Route10 <chr>,
    ## #   Route11 <chr>, `Entrance Type` <chr>, Entry <chr>, `Exit Only` <chr>,
    ## #   Vending <chr>, Staffing <chr>, `Staff Hours` <chr>, ADA <lgl>,
    ## #   `ADA Notes` <chr>, `Free Crossover` <lgl>, `North South Street` <chr>,
    ## #   `East West Street` <chr>, Corner <chr>, `Entrance Latitude` <dbl>,
    ## #   `Entrance Longitude` <dbl>, `Station Location` <chr>, …

``` r
subway_df =
  subway_df |>
  janitor::clean_names() |>
  select(
    line, station_name, station_latitude, station_longitude,
    route1:route11, entry, vending, entrance_type, ada
  ) |>
  mutate(
    entry = case_match(
      entry,
      "YES" ~ TRUE,
      "NO" ~ FALSE
    )
  )
```

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `entry = case_match(entry, "YES" ~ TRUE, "NO" ~ FALSE)`.
    ## Caused by warning:
    ## ! `case_match()` was deprecated in dplyr 1.2.0.
    ## ℹ Please use `recode_values()` instead.

``` r
dim(subway_df)
```

    ## [1] 1868   19

``` r
head(subway_df)
```

    ## # A tibble: 6 × 19
    ##   line     station_name station_latitude station_longitude route1 route2 route3
    ##   <chr>    <chr>                   <dbl>             <dbl> <chr>  <chr>  <chr> 
    ## 1 4 Avenue 25th St                  40.7             -74.0 R      <NA>   <NA>  
    ## 2 4 Avenue 25th St                  40.7             -74.0 R      <NA>   <NA>  
    ## 3 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ## 4 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ## 5 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ## 6 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ## # ℹ 12 more variables: route4 <chr>, route5 <chr>, route6 <chr>, route7 <chr>,
    ## #   route8 <chr>, route9 <chr>, route10 <chr>, route11 <chr>, entry <lgl>,
    ## #   vending <chr>, entrance_type <chr>, ada <lgl>

The cleaned dataset contains 1,868 rows and 19 columns. The retained
variables are: subway line, station name, station latitude/ longitude,
routes, entry, vending, entrance type, and ADA.

I cleaned the column names and selected the required variables, then
converted entry from YES/NO to TRUE/FALSE.

The data are not tidy yet, because route1 through route11 are spread
across multiple columns.

``` r
subway_df |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 465

There are 465 distinct stations.

``` r
subway_df |>
  filter(ada == TRUE) |> 
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 84

84 stations are ADA compliant.

``` r
subway_df |>
  filter(vending == "NO") |>
  pull(entry) |>
  mean()
```

    ## [1] 0.3770492

About 37.7049% station entrances / exits without vending allow entrance.

``` r
subway_tidy =
  subway_df |>
  pivot_longer(
    route1:route11,
    names_to = "route_number",
    names_prefix = "route",
    values_to = "route_name"
  ) |>
  mutate(route_number = as.integer(route_number)) |>
  filter(!is.na(route_name))

head(subway_tidy)
```

    ## # A tibble: 6 × 10
    ##   line     station_name station_latitude station_longitude entry vending
    ##   <chr>    <chr>                   <dbl>             <dbl> <lgl> <chr>  
    ## 1 4 Avenue 25th St                  40.7             -74.0 TRUE  YES    
    ## 2 4 Avenue 25th St                  40.7             -74.0 TRUE  YES    
    ## 3 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ## 4 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ## 5 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ## 6 4 Avenue 36th St                  40.7             -74.0 TRUE  YES    
    ## # ℹ 4 more variables: entrance_type <chr>, ada <lgl>, route_number <int>,
    ## #   route_name <chr>

``` r
subway_tidy |>
  filter(route_name == "A") |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 60

There are 60 distinct stations that serve the A train.

``` r
subway_tidy |>
  filter(route_name == "A", ada == TRUE) |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 17

Of the stations that serve the A train, 17 are ADA compliant.

## Problem 2

## Problem 3
